name: 'Test ROS release action'
description: 'Build a ROS debian release using bloom'
inputs:
  ubuntu:  # id of input
    description: 'Ubuntu version'
    required: true
    default: 'focal'
  distro:  # id of input
    description: 'ROS distro'
    required: true
    default: 'noetic'
runs:
  #using: 'docker'
  #image: 'Dockerfile'
  #args:
  #- ${{ inputs.ubuntu }}
  #- ${{ inputs.distro }}
  using: 'composite'
  steps:
    - id: build
      run: docker build -t release-action --build-arg ubuntu=${{ inputs.ubuntu }} --build-arg distro=${{ inputs.distro }} release-action
      shell: bash
    - id: run
      run: docker run --env GITHUB_WORKSPACE=${{ github.workspace }} -v ${{ github.workspace }}:${{ github.workspace }} release-action
      shell: bash
